apiVersion: v1
kind: Service
metadata:
  name: deliveryapp-lb
  labels:
    app: deliveryapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: deliveryapp
  loadBalancerIP: 35.209.84.144