# Generated by Django 3.1.14 on 2022-03-29 11:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_PICKED', 'Not Picked'), ('PICKED', 'Picked'), ('DELIVERED', 'Delivered')], default='NOT_PICKED', max_length=20)),
                ('delivery_partner', models.BigIntegerField(blank=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('rating', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('pickup_address', models.TextField(default='')),
                ('delivery_address', models.TextField(default='')),
                ('customer_phone_number', models.TextField(default='')),
                ('order_id', models.BigIntegerField(null=True)),
                ('order_details', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user_id', models.BigIntegerField()),
                ('current_location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('last_updated_location_time', models.DateTimeField(blank=True, null=True, verbose_name='Last updated location time')),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
    ]
