# Generated by Django 4.0.1 on 2022-03-11 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 8, 47, 29, 205037)),
        ),
        migrations.AddField(
            model_name='delivery',
            name='location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='location_long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('NOT_PICKED', 'Not Picked'), ('PICKED', 'Picked'), ('DELIVERED', 'Delivered')], default='NOT_PICKED', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
