# Generated by Django 4.0.1 on 2022-03-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='location_long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('NOT_PICKED', 'Not Picked'), ('PICKED', 'Picked'), ('DELIVERED', 'Delivered')], default='NOT_PICKED', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
