# Generated by Django 3.1.14 on 2022-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
