# Generated by Django 4.0.3 on 2022-03-13 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delivery_creation_time_delivery_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 5, 38, 4, 423771)),
        ),
    ]
