# Generated by Django 3.1.14 on 2022-03-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delivery_creation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('current_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Current Latitude')),
                ('current_long', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Current Longitude')),
                ('last_updated_location_time', models.DateTimeField(blank=True, null=True, verbose_name='Last updated location time')),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='location_lat',
            new_name='delivery_location_lat',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='location_long',
            new_name='delivery_location_long',
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_location_long',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
