# Generated by Django 4.0.3 on 2022-03-13 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delivery_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 6, 5, 0, 840153)),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer_phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_id',
            field=models.BigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_address',
            field=models.TextField(default=''),
        ),
    ]
