# Generated by Django 3.1.14 on 2022-03-15 18:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220315_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_location_lat',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_location_long',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_location_lat',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_location_long',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='current_long',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
