# Generated by Django 3.1.14 on 2022-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220315_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_location',
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='phone',
            field=models.TextField(blank=True),
        ),
    ]
