# Generated by Django 3.1.14 on 2022-03-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220328_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_partner',
            field=models.BigIntegerField(blank=True),
        ),
    ]
